apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.8.1
          name: prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-hostpath0
            - mountPath: /etc/prometheus/flink.rules.yml
              name: prometheus-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/stephanesbizzera/PycharmProjects/agnostic/setup/prometheus/prometheus.yml
          name: prometheus-hostpath0
        - hostPath:
            path: /Users/stephanesbizzera/PycharmProjects/agnostic/setup/prometheus/flink.rules.yml
          name: prometheus-hostpath1
status: {}
