apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - env:
            - name: INIT_DAEMON_STEP
              value: setup_spark
            - name: SPARK_LOCAL_IP
              value: spark-master
          image: bde2020/spark-master:3.0.1-hadoop3.2
          name: spark-master
          ports:
            - containerPort: 8079
            - containerPort: 7077
          resources: {}
      hostname: spark-master
      restartPolicy: Always
status: {}
