apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: airflow
    spec:
      containers:
        - args:
            - webserver
          env:
            - name: EXECUTOR
              value: Local
            - name: LOAD_EX
              value: "n"
          image: airflow
          livenessProbe:
            exec:
              command:
                - '[ -f /usr/local/airflow/airflow-webserver.pid ]'
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 30
          name: airflow-container
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: airflow-hostpath0
            - mountPath: /usr/local/airflow/data
              name: airflow-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/stephanesbizzera/PycharmProjects/agnostic/airflow_docker/dags
          name: airflow-hostpath0
        - hostPath:
            path: /Users/stephanesbizzera/PycharmProjects/agnostic/airflow_docker/data
          name: airflow-hostpath1
status: {}
