apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  ports:
    - name: "9096"
      port: 9096
      targetPort: 9093
  selector:
    io.kompose.service: alertmanager
status:
  loadBalancer: {}
