apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka2
    spec:
      containers:
        - args:
            - start-kafka.sh
          env:
            - name: EXTRA_ARGS
              value: -javaagent:/prometheus/jmx_prometheus_javaagent-0.3.1.jar=8080:/prometheus/kafka-0-8-2.yml
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafk2
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://:9093,OUTSIDE://localhost:19093
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_LISTENERS
              value: INSIDE://:9093,OUTSIDE://0.0.0.0:19093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka:2.12-2.2.0
          name: kafka2
          ports:
            - containerPort: 9092
            - containerPort: 8080
            - containerPort: 9093
          resources: {}
          volumeMounts:
            - mountPath: /prometheus
              name: kafka2-hostpath0
            - mountPath: /opt/kafka_2.12-2.2.0/logs
              name: kafka-kafka2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/stephanesbizzera/PycharmProjects/agnostic/cluster/setup/kafka/prometheus
          name: kafka2-hostpath0
        - hostPath:
            path: /Users/stephanesbizzera/PycharmProjects/agnostic/cluster/setup
          name: kafka-kafka2
status: {}
