apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9092
    - name: "8081"
      port: 8081
      targetPort: 8080
    - name: 9093-tcp
      port: 9093
      targetPort: 9093
  selector:
    io.kompose.service: kafka2
status:
  loadBalancer: {}
