apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-manager
  name: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-manager
    spec:
      containers:
        - args:
            - -Dpidfile.path=/dev/null
          env:
            - name: APPLICATION_SECRET
              value: random-secret
            - name: ZK_HOSTS
              value: zookeeper:2181
          image: hlebalbau/kafka-manager:1.3.3.18
          name: kafka-manager
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
