apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flower
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: flower
    spec:
      containers:
        - args:
            - flower
          env:
            - name: EXECUTOR
              value: Celery
          image: puckel/docker-airflow:1.8.1
          name: flower
          ports:
            - containerPort: 5555
          resources: {}
      restartPolicy: Always
status: {}
