apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: socat
  name: socat
spec:
  ports:
    - name: "2375"
      port: 2375
      targetPort: 2375
  selector:
    io.kompose.service: socat
status:
  loadBalancer: {}
